package runtimebundle

import (
	"errors"
	"path/filepath"

	"github.com/evanw/esbuild/pkg/api"
)

const generatedHeader = "// Code generated by go generate ./internal/rush; DO NOT EDIT.\n"

// Build creates the immutable browser-side Rush API embedded by the native
// host. The release binary and npm package are built from the same source tree.
func Build(root string) ([]byte, error) {
	result := api.Build(api.BuildOptions{
		AbsWorkingDir:     root,
		EntryPoints:       []string{filepath.Join(root, "src", "index.ts")},
		Bundle:            true,
		Write:             false,
		Format:            api.FormatIIFE,
		GlobalName:        "__rushBrowserRuntime",
		Platform:          api.PlatformBrowser,
		Target:            api.ES2022,
		MinifyIdentifiers: true,
		MinifySyntax:      true,
		MinifyWhitespace:  true,
		LegalComments:     api.LegalCommentsNone,
		External:          []string{"util"},
		NodePaths:         []string{filepath.Join(root, "node_modules")},
		Define:            map[string]string{"process.env.NODE_ENV": `"test"`},
	})
	if len(result.Errors) > 0 {
		formatted := api.FormatMessages(result.Errors, api.FormatMessagesOptions{Kind: api.ErrorMessage, Color: false})
		return nil, errors.New(formatted[0])
	}
	if len(result.OutputFiles) != 1 {
		return nil, errors.New("esbuild did not emit exactly one browser runtime")
	}
	return append([]byte(generatedHeader), result.OutputFiles[0].Contents...), nil
}
